[tool.poetry]
name = "testpotery"
version = "0.0.1"
description = ""
authors = ["Pawel Stepien"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
emoji = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
